server:
#  port: 8086
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.88.14/fileServer?useUnicode=true&chaeacterEncoding=UTF-8&serverTimeZone=UTC&useSSL=false
    username: root
    password: Lta102103,./
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      location: /
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)